version: "2"

services:
  serf1:
    image: tianxj/serf:v1
    hostname: serf1
    networks:
      cluster:
        ipv4_address: 172.30.0.2
    volumes:
      - ./v/serf1/log:/serf/log
    ports:
      - "7946:7946"
      - "7373:7373"

  serf2:
    image: tianxj/serf:v1
    hostname: serf2
    networks:
      cluster:
        ipv4_address: 172.30.0.3
    volumes:
      - ./v/serf2/log:/serf/log
    ports:
      - "7947:7946"
      - "7374:7373"

networks:
  cluster:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/24
        gateway: 172.30.0.1